version: '3'

services:
  crafty:
    container_name: crafty_container
    image: registry.gitlab.com/crafty-controller/crafty-4:latest
    restart: always
    environment:
        - TZ=Berlin/Europe
    ports:
        - "8443:8443" # HTTPS
        - "8123:8123" # DYNMAP
        - "19132:19132/udp" # BEDROCK
        - "25500-25600:25500-25600" # MC SERV PORT RANGE
    volumes:
        - ${APP_DATA_DIR}/data/backups:/crafty/backups
        - ${APP_DATA_DIR}/data/logs:/crafty/logs
        - ${APP_DATA_DIR}/data/servers:/crafty/servers
        - ${APP_DATA_DIR}/data/config:/crafty/app/config
        - ${APP_DATA_DIR}/data/import:/crafty/import